import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // Manual sidebar for the Physical AI & Humanoid Robotics book
  bookSidebar: [
    {
      type: 'category',
      label: 'Physical AI & Humanoid Robotics',
      items: [
        {
          type: 'category',
          label: 'Module 1: The Robotic Nervous System (ROS 2)',
          items: [
            'module-1-ros-2/chapter-1-architecture',
            'module-1-ros-2/chapter-2-bridging',
            'module-1-ros-2/chapter-3-modeling'
          ],
        },
        {
          type: 'category',
          label: 'Module 2: The Digital Twin (Gazebo & Unity)',
          items: [
            'module-2-digital-twin/chapter-1-gazebo-simulation',
            'module-2-digital-twin/chapter-2-unity-rendering',
            'module-2-digital-twin/chapter-3-sensor-simulation'
          ],
        },
        {
          type: 'category',
          label: 'Module 3: The AI-Robot Brain (NVIDIA Isaac™)',
          items: [
            'module-3-ai-robot-brain/chapter-1-isaac-sim',
            'module-3-ai-robot-brain/chapter-2-isaac-ros',
            'module-3-ai-robot-brain/chapter-3-nav2-path-planning'
          ],
        },
        {
          type: 'category',
          label: 'Module 4: Vision–Language–Action (VLA)',
          items: [
            'module-4-vla/chapter-1-voice-to-action',
            'module-4-vla/chapter-2-cognitive-planning',
            'module-4-vla/chapter-3-capstone'
          ],
        }
      ],
    },
  ],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
